import { createElement } from 'lwc';
import Nms_UsersViewingRecordLive from 'c/nms_UsersViewingRecordLive';

describe('c-nms-users-viewing-record-live', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-nms-users-viewing-record-live', {
            is: Nms_UsersViewingRecordLive
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});